# Node docker image on which this would be run
image: node:latest


#This command is run before actual stages start running
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - npm install --global gulp
  - npm install --save gulp
  - npm install gulp-jasmine
  - npm install gulp-zip
  - npm install gulp-eslint
  - npm install gulp-nodemon
  - npm install gulp-mocha
  - npm install gulp-istanbul
  - npm install request --save 

stages:
  - test
  - build
  - deploy

# lint and test are two different jobs in the same stage.
# This allows us to run these two in parallel and making build faster

# Job 1:
test:
  stage: test
  script:
    - gulp test

# Job 2:
build:
  stage: build
  script:
    - gulp build
    # ToDo: Add coverage

deploy:
  stage: deploy
  script:
    - bash ./deploy/deploy.sh
#job:
#  only:
#    - master
#  stage: deploy
#  script:
#    - bash deploy/deploy.sh
