-- MySQL Script generated by MySQL Workbench
-- jue 31 oct 2019 23:19:50 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';



-- -----------------------------------------------------
-- Table `sa_db`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sa_db`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `sa_db`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Password_` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sa_db`.`Localizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sa_db`.`Localizacion` ;

CREATE TABLE IF NOT EXISTS `sa_db`.`Localizacion` (
  `idLocalizacion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocalizacion`))
ENGINE = InnoDB;

LOCK TABLES `Localizacion` WRITE;
/*!40000 ALTER TABLE `Localizacion` DISABLE KEYS */;
INSERT INTO `Localizacion`(`Nombre`) VALUES ('de'),('en_CA'),('en_US'), ('es_GT'), ('es_MX'), ('fr'),('it'),('ja'),('ko'),('zh');
/*!40000 ALTER TABLE `Localizacion` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `sa_db`.`detalle_usuario_localizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sa_db`.`detalle_usuario_localizacion` ;

CREATE TABLE IF NOT EXISTS `sa_db`.`detalle_usuario_localizacion` (
  `Usuario_idUsuario` INT NOT NULL ,
  `Localizacion_idLocalizacion` INT NOT NULL,
  INDEX `fk_detalle_usuario_localizacion_Usuario_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_detalle_usuario_localizacion_Localizacion1_idx` (`Localizacion_idLocalizacion` ASC),
  CONSTRAINT `fk_detalle_usuario_localizacion_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `sa_db`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_usuario_localizacion_Localizacion1`
    FOREIGN KEY (`Localizacion_idLocalizacion`)
    REFERENCES `sa_db`.`Localizacion` (`idLocalizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;